function MergeMatDataInBin(Info,S,Data2import,Range, Offset,VideoAbsStartDateNum)
%this function permit to merge date from matlab (mat file) into binary file to be opened in slipanalysis, this ill generate a new exp file and bin file
%Info came from loadEXP and containt all the information from the experience
%S is a structure that containt all the field and data generated by SleepMov, S(n).Name is the chan name, S(n).Data are the data, S(n).time is the time laspes from the first video frame in min
%Data2import containt a matrix with the index of the dataS to merge with the in the binary files
%Range and offset are matrix containing the range and offet of the data to import, if empty the adat are defined automattically
%VideoAbsStartDateNum is the absoluted datetime of the video start

%convert S.data in int16 or uint16
AllDataok=cat(2,S(Data2import).Data);
AllDataok=abs(AllDataok);

if isempty(Range)==0 || isempty(Offset)==0
    Range=nanmax(AllDataok,[],1)-nanmin(max(AllDataok,[],1));
    idrangezero=Range==0 | isnan(Range) ;
    Offset=Range/2+nanmin(max(AllDataok,[],1));
    %force to 1 and 0 the range and offset for empty val
    Range(idrangezero)=1;
    Offset(idrangezero)=0;
end


%duplicate expfile
paramsOldEXP.FileInfo=Info;
NewEXPFilename=[Info.ExpFileName(1:end-4) '_2'];

[NewFileInfo,Status]=DuplicateHypnoAndExp(paramsOldEXP,NewEXPFilename);


if Status==1
    
    %for each binfile
    
    for nbin=1:length(NewFileInfo.BinFiles)
        Fs=NewFileInfo.Fs;
        T0=0;
        Te=inf;
        NbCh=NewFileInfo.NbRecChan;
        skip=[];
        Type=NewFileInfo.Precision;
        
        fid=fopen(fullfile(NewFileInfo.FilesDir,NewFileInfo.BinFiles(nbin).FileName),'r+');
        BinData=fread(fid,[NbCh,inf],Type);
        fclose(fid);
        
        %reinterpolation of the data(
        
        AbsTStart=0
        EndTStart=0
       
        
    end
    
    
end

